// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// NotificationRequest defines model for NotificationRequest.
type NotificationRequest struct {
	// Message The message content of the notification.
	Message string `json:"message" validate:"required"`

	// RoutingKey The routing key used to categorize or route the notification.
	RoutingKey *string `json:"routing_key,omitempty"`

	// ServiceId The ID of the service requesting the notification.
	ServiceId string `json:"service_id" validate:"required"`

	// Subject The subject of the notification.
	Subject string `json:"subject" validate:"required"`
}

// SendNotificationJSONRequestBody defines body for SendNotification for application/json ContentType.
type SendNotificationJSONRequestBody = NotificationRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SendNotificationWithBody request with any body
	SendNotificationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SendNotification(ctx context.Context, body SendNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) SendNotificationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendNotificationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendNotification(ctx context.Context, body SendNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendNotificationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSendNotificationRequest calls the generic SendNotification builder with application/json body
func NewSendNotificationRequest(server string, body SendNotificationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSendNotificationRequestWithBody(server, "application/json", bodyReader)
}

// NewSendNotificationRequestWithBody generates requests for SendNotification with any type of body
func NewSendNotificationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/notify")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SendNotificationWithBodyWithResponse request with any body
	SendNotificationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendNotificationResponse, error)

	SendNotificationWithResponse(ctx context.Context, body SendNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*SendNotificationResponse, error)
}

type SendNotificationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *struct {
		Details *[]string `json:"details,omitempty"`
		Error   string    `json:"error,omitempty"`
	}
	JSON500 *struct {
		Error *string `json:"error,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r SendNotificationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SendNotificationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// SendNotificationWithBodyWithResponse request with arbitrary body returning *SendNotificationResponse
func (c *ClientWithResponses) SendNotificationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendNotificationResponse, error) {
	rsp, err := c.SendNotificationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendNotificationResponse(rsp)
}

func (c *ClientWithResponses) SendNotificationWithResponse(ctx context.Context, body SendNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*SendNotificationResponse, error) {
	rsp, err := c.SendNotification(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendNotificationResponse(rsp)
}

// ParseSendNotificationResponse parses an HTTP response from a SendNotificationWithResponse call
func ParseSendNotificationResponse(rsp *http.Response) (*SendNotificationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SendNotificationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Details *[]string `json:"details,omitempty"`
			Error   string    `json:"error,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest struct {
			Error *string `json:"error,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xVwY4bNwz9FYHtoQXGYydpL3PbtAXqS7FoewsWgSrRNrMzkkJy3HUX/vdCGtmx40ET",
	"oHuTOSL1Hvn4/AwuDikGDCrQPYO4HQ62HH+LShtyVimG3/HjiKI5bL2nHLL9PceErIQC3cb2gg2ki9Az",
	"DChit5iPHsUxpZwIHfy5Q1M/GheDYlATN0Z3aMLFqy00gE92SD1CB3fGMSk52xtkjmx2Vkx0bmRGbyiU",
	"dEHek8OcqYeU00SZwhYaeFpEm2jhoscthgU+KduF2m2Burc9eas5gfHjSIwejscGOI5KYfv+EQ/zNOoF",
	"84gHMwp6o9E4q7iNTP+giVxu4Be4FUKt7ZH1BvmxgcrqPfl5EOufT+2rNw1PA8vI/vvlmvDq9ZuXapmM",
	"f31Ap/NI68cvT/un06x/ya15GWx5nqdf3bvLrn5C3ZxV+3B+M06fSgEKm3hL7e5+bTaRjWDwueeXvMTs",
	"yRa2yxI+GAw+RQpaVEpa+P6KPKCYu/s1NLBHlqnwq3bVrrIEYsJgE0EHb9pVm4eVrO4K2Vo2H1OUmcb/",
	"gcGLsVeozN+ku4IqcdyTR288qqVesoKLlBI62hD6y6XK613y174WvrQJmBqMom+jL4DqdhfjSKmv95Yf",
	"JAM72U0+fcu4gQ6+WX7yo2U1o+WcE5Vh3OrriqK3ajObPJUWyvQlxSCTO71erW5bdflUzlMjo3Moshn7",
	"/pBr/DClfTWxa0usPc7Hs9YvlWhIzFmjZy1eRR8aIMWh1LhxihqwzLagLcZy9RqsQ9kOQyGN2piBRLJk",
	"T/XNhrD3Mu+g27jIwYU8UlrENP0PLIqYkaFTHvF4nN2b6za/tf5kUea7uqy54wWufJ+R//i/+jzLW5GD",
	"7Yuckae3bml+Ff7ZWtX9hsHyoS7HZ0s3lZpyBLp3n6vvnqMfXdVevgQNjNxDBzvVJN1yaRO1u2IVbWXW",
	"ujjA8eH4bwAAAP//ZpYjv8oHAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
