CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    service_id TEXT NOT NULL,
    insertion_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    retry_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    retries INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE schema_version
(
    version INTEGER NOT NULL
);
